# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Nebula
        uses: actions/checkout@v2
        with:
          repository: TeamKun/ModNebula

      - name: Checkout Packs
        uses: actions/checkout@v2
        with:
          path: ./packs

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jre
          architecture: x64

      - name: Create .env
        run: echo -e "JAVA_EXECUTABLE=$(which java)\nROOT=$GITHUB_WORKSPACE/packs\nBASE_URL=https://raw.githubusercontent.com/$GITHUB_REPOSITORY/deploy/" > .env

      - name: Setup Nebula
        run: |
          npm i
          npm build ./
          npm run build

      - name: Generate Distribution
        run: node dist/index.js generate distro

      - name: Git commit files
        working-directory: ./packs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Auto-Generate Nebula Distribution" -a

      - name: Git push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: deploy
          directory: ./packs
          force: true
